# Generated by Django 4.2.11 on 2024-03-18 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_alter_claim_created_at_alter_claim_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="last_seen",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
