# Generated by Django 4.2.11 on 2024-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
