# Generated by Django 4.2.11 on 2024-03-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
    ]
